name: DeployStaticSite

on:
  push:
    branches: [ "main" ]   # Runs when code is pushed to main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: San/checkout@v4

      - name: Deploy to GitHub Pages
        uses: https://github.com/vallirathi/San
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
